# Generated by Django 4.2.3 on 2023-08-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_emp_comm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emp",
            name="COMM",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
